export default Object.freeze({
  CHANGE_USERNAME: 'CHANGE_USERNAME',
  ASYNC_SUCCESS: 'ASYNC_SUCCESS',
  ASYNC_FAILURE: 'ASYNC_FAILURE',
  ASYNC_IS_LOADING: 'ASYNC_IS_LOADING',
  BACKEND_SUCCESS: 'BACKEND_SUCCESS',
  BACKEND_FAILURE: 'BACKEND_FAILURE',
  BACKEND_IS_LOADING: 'BACKEND_IS_LOADING',
});