export default Object.freeze({
  ASYNC_SUCCESS: 'ASYNC_SUCCESS',
  ASYNC_ERROR: 'ASYNC_ERROR',
  ASYNC_LOADING: 'ASYNC_LOADING',
  NORMAL_ACTION: 'NORMAL_ACTION',
  DB_MESSAGE_STATUS: 'DB_MESSAGE_STATUS',
  DB_MESSAGE_CREATION_LOADING:  'DB_MESSAGE_CREATION_LOADING',
  DB_MESSAGE_GET_LOADING: 'DB_MESSAGE_GET_LOADING',
  DB_SAVE_MESSAGES: 'DB_SAVE_MESSAGES',
});